[package]
name = "spacer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3", features = ["derive"] }
anyhow = "1.0"
terminal_size = "0.2"
time = {version = "0.3", features = ["local-offset", "formatting", "macros"] }
lazy_static = "1.4"
owo-colors = "3"
