name: Build

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "LICENSE"

jobs:
  # Ensure that the project could be successfully compiled
  cargo_check:
    name: Check Code Compiles
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo check --all

  # Run the `rustfmt` code formatter
  rustfmt:
    name: Rustfmt [Formatter]
    needs: cargo_check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - run: cargo fmt --all -- --check

  # Run the `clippy` linting tool
  clippy:
    name: Clippy [Linter]
    needs: cargo_check
    runs-on: ubuntu-22.04
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - run: cargo clippy --all-targets --all-features -- -D clippy::all

  cargo_audit:
    name: Cargo Audit [Security]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/audit@v1

  test:
    needs: [cargo_check, rustfmt, clippy]
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo test

  github_build:
    # if: startsWith(github.ref, 'refs/tags/v')
    name: Build release binaries
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - aarch64-apple-darwin
          - aarch64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
            name: spacer-x86_64-unknown-linux-gnu.tar.gz
          - target: x86_64-unknown-linux-musl
            os: ubuntu-20.04
            name: spacer-x86_64-unknown-linux-musl.tar.gz
          - target: x86_64-apple-darwin
            os: macOS-latest
            name: spacer-x86_64-apple-darwin.tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: spacer-x86_64-pc-windows-msvc.zip
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-20.04
            name: spacer-aarch64-unknown-linux-gnu.tar.gz
          - target: aarch64-unknown-linux-musl
            os: ubuntu-20.04
            name: spacer-aarch64-unknown-linux-musl.tar.gz
          - target: aarch64-apple-darwin
            os: macOS-latest
            name: spacer-aarch64-apple-darwin.tar.gz
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            name: spacer-aarch64-pc-windows-msvc.zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true

      - name: Prepare build artifacts [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ matrix.name }} spacer.exe
          cd -

      - name: Prepare build artifacts [-nix]
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../${{ matrix.name }} spacer
          cd -

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  github_release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Create GitHub Release
    needs: [test, github_build, cargo_audit]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Download releases from github_build
        uses: actions/download-artifact@v4
        with:
          name: spacer-x86_64-unknown-linux-gnu.tar.gz
          path: .
      - name: Download releases from github_build
        uses: actions/download-artifact@v4
        with:
          name: spacer-x86_64-unknown-linux-musl.tar.gz
          path: .
      - name: Download releases from github_build
        uses: actions/download-artifact@v4
        with:
          name: spacer-x86_64-apple-darwin.tar.gz
          path: .
      - name: Download releases from github_build
        uses: actions/download-artifact@v4
        with:
          name: spacer-x86_64-pc-windows-msvc.zip
          path: .
      - name: Download releases from github_build
        uses: actions/download-artifact@v4
        with:
          name: spacer-aarch64-unknown-linux-gnu.tar.gz
          path: .
      - name: Download releases from github_build
        uses: actions/download-artifact@v4
        with:
          name: spacer-aarch64-unknown-linux-musl.tar.gz
          path: .
      - name: Download releases from github_build
        uses: actions/download-artifact@v4
        with:
          name: spacer-aarch64-apple-darwin.tar.gz
          path: .
      - name: Download releases from github_build
        uses: actions/download-artifact@v4
        with:
          name: spacer-aarch64-pc-windows-msvc.zip
          path: .

      - name: Generate checksums
        run: for file in spacer-*; do openssl dgst -sha256 -r "$file" > "${file}.sha256"; done

      - name: Create GitHub release ${{ matrix.target }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            spacer-x86_64-unknown-linux-gnu.tar.gz
            spacer-x86_64-unknown-linux-gnu.tar.gz.sha256
            spacer-x86_64-unknown-linux-musl.tar.gz
            spacer-x86_64-unknown-linux-musl.tar.gz.sha256
            spacer-x86_64-apple-darwin.tar.gz
            spacer-x86_64-apple-darwin.tar.gz.sha256
            spacer-x86_64-pc-windows-msvc.zip
            spacer-x86_64-pc-windows-msvc.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cargo_publish:
    needs: [test, cargo_audit]
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish Cargo Package
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo login $CRATES_IO_TOKEN
      - run: cargo publish
    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
